apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::150585151909:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters    
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::150585151909:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-NUNFG7IX1DES
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-01T21:24:09Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "880"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 8fa5d637-4c65-449a-84cd-1de2c90da89e
